### ISSUE TITLE
BinSkim fails with AccessViolationException while scanning linux_arm build

### ISSUE THREAD

**Issue by dagood** [microsoft/go#806]
```
  Analyze:
    Running BinSkim 1.9.5
    ------------------------------------------------------------------------------
    D:\a\_work\1\.gdn\i\nuget\Microsoft.CodeAnalysis.BinSkim.1.9.5\tools\netcoreapp3.1\win-x64\BinSkim.exe analyze --config D:\a\_work\1\s\eng\compliance\Guardian\BinSkimConfig.xml --hashes --statistics --sarif-output-version OneZeroZero --output D:\a\_work\1\.gdn\.r\binskim\001\binskim.sarif @D:\a\_work\1\.gdn\.r\binskim\001\.gdntoolinput
    Analyzing...
[...]
    D:\a\_work\1\a\artifacts\go.linux-armv6l.tar.gz.extracted\go\pkg\tool\linux_arm\buildid : error ERR997.ExceptionLoadingAnalysisTarget : Could not load analysis target 'buildid'.
    D:\a\_work\1\a\artifacts\go.linux-armv6l.tar.gz.extracted\go\pkg\tool\linux_arm\cgo : error ERR997.ExceptionLoadingAnalysisTarget : Could not load analysis target 'cgo'.
[Error]     Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
[Error]        at System.Runtime.InteropServices.Marshal.ReadInt32(IntPtr, Int32)
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader.ReadUint()
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader.ReadLength(Boolean ByRef)
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfCommonInformationEntry.ParseEntry(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Byte, Int32)
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfCommonInformationEntry.ParseAll(Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfMemoryReader, Byte)
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfSymbolProvider.ParseCommonInformationEntries(Byte[], Byte[], Microsoft.CodeAnalysis.BinaryParsers.Dwarf.DwarfExceptionHandlingFrameParsingInput)
[Error]        at Microsoft.CodeAnalysis.BinaryParsers.ElfBinary..ctor(System.Uri, System.String)
[Error]        at Microsoft.CodeAnalysis.IL.Sdk.BinaryTargetManager.GetBinaryFromFile(System.Uri, System.String, System.String, Boolean)
[Error]        at Microsoft.CodeAnalysis.IL.Sdk.BinaryAnalyzerContext.get_Binary()
[Error]        at Microsoft.CodeAnalysis.IL.Sdk.BinaryAnalyzerContext.get_TargetLoadException()
[Error]        at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].DetermineApplicabilityAndAnalyze(System.__Canon, System.Collections.Generic.IEnumerable`1<Microsoft.CodeAnalysis.Sarif.Driver.Skimmer`1<System.__Canon>>, System.Collections.Generic.ISet`1<System.String>)
[Error]        at Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2+<AnalyzeTargetAsync>d__40[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
[Error]        at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
[Error]        at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Boolean, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[Microsoft.CodeAnalysis.Sarif.Driver.MultithreadedAnalyzeCommandBase`2+<AnalyzeTargetAsync>d__40[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]], Sarif.Driver, Version=2.4.15.0, Culture=neutral, PublicKeyToken=21a5e83f6f5bb844]].MoveNext(System.Threading.Thread)
[Error]        at System.Threading.ThreadPoolWorkQueue.Dispatch()
    Tool run time: 37.5255022 seconds
    ------------------------------------------------------------------------------
    BinSkim completed with exit code 57005
[Error]     Error running binskim job: 1 of 1
[Error]     GuardianErrorExitCodeException: binskim completed with an Error exit code: 57005. Please refer to https://github.com/Microsoft/binskim#command-line-documentation for more info.
    ------------------------------------------------------------------------------
```

I was able to repro locally and submitted a bug report to BinSkim:

* https://github.com/microsoft/binskim/issues/743

**Comment by dagood** [comment]
Haven't noticed this recently.
